// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/piopon/domesticity/services/text-event-service/sdk/models"
)

// NewUpdateEventParams creates a new UpdateEventParams object
// with the default values initialized.
func NewUpdateEventParams() *UpdateEventParams {
	var ()
	return &UpdateEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEventParamsWithTimeout creates a new UpdateEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateEventParamsWithTimeout(timeout time.Duration) *UpdateEventParams {
	var ()
	return &UpdateEventParams{

		timeout: timeout,
	}
}

// NewUpdateEventParamsWithContext creates a new UpdateEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateEventParamsWithContext(ctx context.Context) *UpdateEventParams {
	var ()
	return &UpdateEventParams{

		Context: ctx,
	}
}

// NewUpdateEventParamsWithHTTPClient creates a new UpdateEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateEventParamsWithHTTPClient(client *http.Client) *UpdateEventParams {
	var ()
	return &UpdateEventParams{
		HTTPClient: client,
	}
}

/*UpdateEventParams contains all the parameters to send to the API endpoint
for the update event operation typically these are written to a http.Request
*/
type UpdateEventParams struct {

	/*Body
	  Event data structure to update or create.
	Note: the id field is ignored by update and create operations

	*/
	Body *models.Event
	/*ID
	  The id of the event for which the operation relates

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update event params
func (o *UpdateEventParams) WithTimeout(timeout time.Duration) *UpdateEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update event params
func (o *UpdateEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update event params
func (o *UpdateEventParams) WithContext(ctx context.Context) *UpdateEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update event params
func (o *UpdateEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update event params
func (o *UpdateEventParams) WithHTTPClient(client *http.Client) *UpdateEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update event params
func (o *UpdateEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update event params
func (o *UpdateEventParams) WithBody(body *models.Event) *UpdateEventParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update event params
func (o *UpdateEventParams) SetBody(body *models.Event) {
	o.Body = body
}

// WithID adds the id to the update event params
func (o *UpdateEventParams) WithID(id int64) *UpdateEventParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update event params
func (o *UpdateEventParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
