basePath: /
consumes:
- application/json
definitions:
  Event:
    description: Event defines the structure for an API event
    properties:
      _id:
        $ref: '#/definitions/ObjectID'
      category:
        description: The category of event
        maxLength: 255
        type: string
        x-go-name: Category
      content:
        description: The event main content (text message)
        maxLength: 10000
        type: string
        x-go-name: Content
      date:
        $ref: '#/definitions/TimeSpan'
      icon:
        description: The icon of event
        maxLength: 255
        type: string
        x-go-name: Icon
      owner:
        description: The title of event
        maxLength: 255
        type: string
        x-go-name: Owner
      title:
        description: The title of event
        maxLength: 255
        type: string
        x-go-name: Title
    required:
    - title
    - icon
    - owner
    - date
    - category
    type: object
    x-go-package: github.com/piopon/domesticity/services/text-event-service/src/model
  Events:
    description: Events is a type definition for slice of Event pointers
    items:
      $ref: '#/definitions/Event'
    type: array
    x-go-package: github.com/piopon/domesticity/services/text-event-service/src/model
  GenericError:
    description: GenericError is a generic error message returned by a server
    properties:
      message:
        type: string
        x-go-name: Message
    type: object
    x-go-package: github.com/piopon/domesticity/services/text-event-service/src/model
  ObjectID:
    items:
      format: uint8
      type: integer
    title: ObjectID is the BSON ObjectID type.
    type: array
    x-go-package: go.mongodb.org/mongo-driver/bson/primitive
  TimeSpan:
    description: TimeSpan is an struct representing event start and end time
    properties:
      start:
        description: The event start time in RFC3339 standard ("2006-01-02T15:04:05Z07:00")
        format: date-time
        type: string
        x-go-name: Start
      stop:
        description: The event stop time in RFC3339 standard ("2006-01-02T15:04:05Z07:00")
        format: date-time
        type: string
        x-go-name: Stop
    required:
    - start
    - stop
    type: object
    x-go-package: github.com/piopon/domesticity/services/text-event-service/src/model
  ValidationError:
    description: ValidationError is a collection of validation error messages
    properties:
      messages:
        items:
          type: string
        type: array
        x-go-name: Messages
    type: object
    x-go-package: github.com/piopon/domesticity/services/text-event-service/src/model
info:
  contact:
    email: piopon.github@gmail.com
    name: Piotr Ponikowski
  description: Documentation for Text Event Service API used by Domesticity application
  license:
    name: GPL-3.0
    url: https://opensource.org/licenses/GPL-3.0
  title: Domesticity Text Event Service API
  version: 1.0.0
paths:
  /docs:
    get:
      description: |-
        Returns a HTML and JS page with this documentation<br>
        NOTE: This page was auto-generated by ReDoc (https://github.com/Redocly/redoc)
      operationId: getDocumentation
      responses:
        "200":
          $ref: '#/responses/responseDocumentation'
      tags:
      - utilities
  /event/{id}:
    get:
      description: Returns a event with provided id
      operationId: getEvent
      parameters:
      - description: |-
          The id of the event for which the operation relates<br>
          NOTE: The type is primitive.ObjectID which is the BSON ObjectID type
        in: path
        items:
          format: int64
          type: integer
        name: id
        required: true
        type: array
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/responseGetEvent'
        "404":
          $ref: '#/responses/errorNotFound'
        "500":
          $ref: '#/responses/errorInternal'
      tags:
      - events
  /events:
    get:
      description: Returns a list of currently stored events (all if no query params is used or filtered otherwise)
      operationId: getEvents
      parameters:
      - description: The number of items to return.
        format: int64
        in: query
        minimum: 0
        name: limit
        type: integer
        x-go-name: Limit
      - description: The number of items to skip before starting to collect the result set.
        format: int64
        in: query
        minimum: 0
        name: offset
        type: integer
        x-go-name: Offset
      - description: The string which has to be included (not exact match) in searched event title
        in: query
        name: title
        type: string
        x-go-name: Title
      - description: The string which has to match exact searched event owner
        in: query
        name: owner
        type: string
        x-go-name: Owner
      - description: The start date of seached event in format YYYY-MM-DD
        format: date-time
        in: query
        name: dayStart
        type: string
        x-go-name: DayStart
      - description: The end date of seached event in format YYYY-MM-DD
        format: date-time
        in: query
        name: dayStop
        type: string
        x-go-name: DayStop
      - description: The month date for which to search events in format YYYY-MM-DD (day component is not used)
        format: date-time
        in: query
        name: inMonth
        type: string
        x-go-name: InMonth
      - description: The string which has to match exact searched event category
        in: query
        name: category
        type: string
        x-go-name: Category
      - description: The string which has to be included (not exact match) in searched event content
        in: query
        name: content
        type: string
        x-go-name: Content
      responses:
        "200":
          $ref: '#/responses/responseGetEvents'
        "400":
          $ref: '#/responses/errorBadQuery'
        "500":
          $ref: '#/responses/errorInternal'
      tags:
      - events
    post:
      description: Creates a new event and adds it to DB
      operationId: addEvent
      parameters:
      - description: |-
          Event data structure to update or create.
          Note: the id field is ignored by update and create operations
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        "200":
          $ref: '#/responses/responsePostEvent'
        "400":
          $ref: '#/responses/errorBadQuery'
        "422":
          $ref: '#/responses/errorValidation'
        "500":
          $ref: '#/responses/errorInternal'
      tags:
      - events
  /events/{id}:
    delete:
      description: Deletes an event from DB by specified ID parameter
      operationId: deleteEvent
      parameters:
      - description: |-
          The id of the event for which the operation relates<br>
          NOTE: The type is primitive.ObjectID which is the BSON ObjectID type
        in: path
        items:
          format: int64
          type: integer
        name: id
        required: true
        type: array
        x-go-name: ID
      responses:
        "204":
          $ref: '#/responses/responseNoContent'
        "400":
          $ref: '#/responses/errorBadQuery'
      tags:
      - events
    put:
      description: Updates an event in DB by specified ID parameter
      operationId: updateEvent
      parameters:
      - description: |-
          The id of the event for which the operation relates<br>
          NOTE: The type is primitive.ObjectID which is the BSON ObjectID type
        in: path
        items:
          format: int64
          type: integer
        name: id
        required: true
        type: array
        x-go-name: ID
      - description: |-
          Event data structure to update or create.
          Note: the id field is ignored by update and create operations
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        "200":
          $ref: '#/responses/responsePutEvent'
        "400":
          $ref: '#/responses/errorBadQuery'
        "422":
          $ref: '#/responses/errorValidation'
        "500":
          $ref: '#/responses/errorInternal'
      tags:
      - events
  /resources/swagger.yaml:
    get:
      description: |-
        Returns swagger.yaml configuration file needed for generating this documentation<br>
        NOTE: This file should be located in resources directory
      operationId: getSwagger
      responses:
        "200":
          $ref: '#/responses/responseSwagger'
        "404":
          $ref: '#/responses/errorSwagger'
      tags:
      - utilities
produces:
- application/json
responses:
  errorBadQuery:
    description: Error with JSON message returned in body when bad request was invoked
    schema:
      $ref: '#/definitions/GenericError'
  errorInternal:
    description: Error with JSON message returned in body when internal server error occurs
    schema:
      $ref: '#/definitions/GenericError'
  errorNotFound:
    description: Error with JSON message returned in body when desired item is not found
    schema:
      $ref: '#/definitions/GenericError'
  errorSwagger:
    description: Error with no specific content returned when no swagger.yaml is found
  errorValidation:
    description: Error with JSON messages returned in body when validation error occurs
    schema:
      $ref: '#/definitions/ValidationError'
  responseDocumentation:
    description: Response with a HTML documentation file in body
  responseGetEvent:
    description: Response with single event from DB (selected by ID parameter in path param)
    schema:
      $ref: '#/definitions/Event'
  responseGetEvents:
    description: Response with all or filtered events from DB (filter depends on query params)
    schema:
      $ref: '#/definitions/Events'
  responseNoContent:
    description: Response with no specific content in body (status indicates success)
  responsePostEvent:
    description: Response with currently created event which was added to DB
    schema:
      $ref: '#/definitions/Event'
  responsePutEvent:
    description: Response with currently updated event stored in DB (selected by ID parameter in path param)
    schema:
      $ref: '#/definitions/Event'
  responseSwagger:
    description: Response with a YAML swagger configuration file in body
schemes:
- http
swagger: "2.0"
