// Code generated by go-swagger; DO NOT EDIT.

package utilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDocumentationParams creates a new GetDocumentationParams object
// with the default values initialized.
func NewGetDocumentationParams() *GetDocumentationParams {

	return &GetDocumentationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDocumentationParamsWithTimeout creates a new GetDocumentationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDocumentationParamsWithTimeout(timeout time.Duration) *GetDocumentationParams {

	return &GetDocumentationParams{

		timeout: timeout,
	}
}

// NewGetDocumentationParamsWithContext creates a new GetDocumentationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDocumentationParamsWithContext(ctx context.Context) *GetDocumentationParams {

	return &GetDocumentationParams{

		Context: ctx,
	}
}

// NewGetDocumentationParamsWithHTTPClient creates a new GetDocumentationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDocumentationParamsWithHTTPClient(client *http.Client) *GetDocumentationParams {

	return &GetDocumentationParams{
		HTTPClient: client,
	}
}

/*GetDocumentationParams contains all the parameters to send to the API endpoint
for the get documentation operation typically these are written to a http.Request
*/
type GetDocumentationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get documentation params
func (o *GetDocumentationParams) WithTimeout(timeout time.Duration) *GetDocumentationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get documentation params
func (o *GetDocumentationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get documentation params
func (o *GetDocumentationParams) WithContext(ctx context.Context) *GetDocumentationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get documentation params
func (o *GetDocumentationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get documentation params
func (o *GetDocumentationParams) WithHTTPClient(client *http.Client) *GetDocumentationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get documentation params
func (o *GetDocumentationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDocumentationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
