// Code generated by go-swagger; DO NOT EDIT.

package utilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDocumentationReader is a Reader for the GetDocumentation structure.
type GetDocumentationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDocumentationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDocumentationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDocumentationOK creates a GetDocumentationOK with default headers values
func NewGetDocumentationOK() *GetDocumentationOK {
	return &GetDocumentationOK{}
}

/*GetDocumentationOK handles this case with default header values.

Response with a HTML documentation file in body
*/
type GetDocumentationOK struct {
}

func (o *GetDocumentationOK) Error() string {
	return fmt.Sprintf("[GET /docs][%d] getDocumentationOK ", 200)
}

func (o *GetDocumentationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
