basePath: /
consumes:
- application/json
info:
  description: Documentation for Text Event Service API used by Domesticity application
  title: Domesticity Text Event Service API
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
