version: '3.8'

services:
  server:
    build:
      context: .
      args:
        - LD_FLAGS=$LD_FLAGS
        - EXPOSED_PORTS=9999
      dockerfile: Dockerfile
      target: bin
    ports:
      - 9999:9999
    container_name: events
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.2-bionic
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    container_name: mongo
    restart: always

volumes:
  mongodb_data: