basePath: /
consumes:
- application/json
definitions:
  Event:
    description: Event defines the structure for an API event
    properties:
      category:
        type: string
        x-go-name: Category
      content:
        type: string
        x-go-name: Content
      date:
        $ref: '#/definitions/TimeSpan'
      id:
        format: int64
        type: integer
        x-go-name: ID
      owner:
        type: string
        x-go-name: Owner
      title:
        type: string
        x-go-name: Title
    type: object
    x-go-package: github.com/piopon/domesticity/services/text-event-service/model
  Events:
    description: Events is a type definition for slice of Event pointers
    items:
      $ref: '#/definitions/Event'
    type: array
    x-go-package: github.com/piopon/domesticity/services/text-event-service/model
  TimeSpan:
    description: TimeSpan is an struct representing event start and end time
    properties:
      start:
        format: date-time
        type: string
        x-go-name: Start
      stop:
        format: date-time
        type: string
        x-go-name: Stop
    type: object
    x-go-package: github.com/piopon/domesticity/services/text-event-service/model
info:
  contact:
    email: piopon.github@gmail.com
    name: Piotr Ponikowski
  description: Documentation for Text Event Service API used by Domesticity application
  license:
    name: GPL-3.0
    url: https://opensource.org/licenses/GPL-3.0
  title: Domesticity Text Event Service API
  version: 1.0.0
paths:
  /docs:
    get:
      description: |-
        Returns a HTML and JS page with this documentation<br>
        NOTE: This page was auto-generated by ReDoc (https://github.com/Redocly/redoc)
      operationId: getDocumentation
      responses:
        "204":
          $ref: '#/responses/responseNoContent'
      tags:
      - utilities
  /event/{id}:
    get:
      description: Returns a event with provided id
      operationId: getEvent
      parameters:
      - description: The id of the event for which the operation relates
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/responseEvent'
        "404":
          $ref: '#/responses/errorNotFound'
        "500":
          $ref: '#/responses/errorInternal'
      tags:
      - events
  /events:
    get:
      description: Returns a list of currently stored events (all or filtered)
      operationId: getEvents
      responses:
        "200":
          $ref: '#/responses/responseEvents'
        "400":
          $ref: '#/responses/errorBadQuery'
        "500":
          $ref: '#/responses/errorInternal'
      tags:
      - events
    post:
      description: Creates a new event and adds it to DB
      operationId: addEvent
      parameters:
      - description: |-
          Event data structure to update or create.
          Note: the id field is ignored by update and create operations
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        "200":
          $ref: '#/responses/responseEvent'
        "400":
          $ref: '#/responses/errorBadQuery'
      tags:
      - events
  /events/{id}:
    delete:
      description: Deletes an event from DB by specified ID parameter
      operationId: deleteEvent
      parameters:
      - description: The id of the event for which the operation relates
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "204":
          $ref: '#/responses/responseNoContent'
        "400":
          $ref: '#/responses/errorBadQuery'
      tags:
      - events
    put:
      description: Updates an event in DB by specified ID parameter
      operationId: updateEvent
      parameters:
      - description: The id of the event for which the operation relates
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: |-
          Event data structure to update or create.
          Note: the id field is ignored by update and create operations
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        "204":
          $ref: '#/responses/responseNoContent'
        "400":
          $ref: '#/responses/errorBadQuery'
      tags:
      - events
  /scripts/swagger.yaml:
    get:
      description: |-
        Returns swagger.yaml configuration file needed for generating this documentation<br>
        NOTE: This file should be located in scripts directory
      operationId: getSwagger
      responses:
        "204":
          $ref: '#/responses/responseNoContent'
      tags:
      - utilities
produces:
- application/json
responses:
  errorBadQuery:
    description: Error message returned as a string when bad request was invoked (400)
  errorInternal:
    description: Error message returned as a string when internal server error occurs (500)
  errorNotFound:
    description: Error message returned as a string when desired item is not found (404)
  responseEvent:
    description: ResponseEvent with single event from DB (depends on ID parameter)
    schema:
      $ref: '#/definitions/Event'
  responseEvents:
    description: ResponseEvents with all or filtered events from DB (depends on query params)
    schema:
      $ref: '#/definitions/Events'
  responseNoContent:
    description: ResponseNoContent is returned when no specific response is needed
schemes:
- http
swagger: "2.0"
